### ISSUE TITLE
Error while publishing dex module

### ISSUE THREAD

**Issue by thaodx** [interest-protocol/sui-defi#1]
After successfully publish IPX module, i've set the address of ipx on dex/Move.toml file and tried to publish dex module but got below error:

error[E03002]: unbound module
   ┌─ ./sources/core.move:15:7
   │
15 │   use ipx::curve::{is_curve, is_volatile, Stable, Volatile};
   │       ^^^^^^^^^^ Invalid 'use'. Unbound module: '(ipx=0xDAE342237FDB708942BB87216C2746BAD26DCF82D25C3A43407FC737C94E4DD2)::curve'

error[E03004]: unbound type
    ┌─ ./sources/core.move:169:20
    │
169 │     ): Coin<LPCoin<Volatile, X, Y>> {
    │                    ^^^^^^^^ Unbound type 'Volatile' in current scope

error[E03004]: unbound type
    ┌─ ./sources/core.move:180:53
    │
180 │       let type = utils::get_coin_info_string<LPCoin<Volatile, X, Y>>();
    │                                                     ^^^^^^^^ Unbound type 'Volatile' in current scope
......

**Comment by josemvcerqueira** [comment]
Hello can you show your Move.tml

**Comment by thaodx** [comment]
> Hello @thaodx
> 
> Thank you for raising this issue and testing our code.
> 
> I pushed a fix in this commit.
> 
> [7e8c065](https://github.com/interest-protocol/sui-defi/commit/7e8c0657110500cc22e779a4448f1bfb9c0efac3)

Thank you @josemvcerqueira , i can now publish the dex successfully.
