### ISSUE TITLE
Could not create stable pool

### ISSUE THREAD

**Issue by thaodx** [interest-protocol/sui-defi#2]
When trying to create a stable pool using `create_s_pool` function, i got this error:

> Error calling module: Failure {
>     error: "MovePrimitiveRuntimeError(MoveLocationOpt(Some(MoveLocation { module: ModuleId { address: 366a6d402c05d5fce5fdc8b675e7bc6d02d52147195e625c702c313d85922ba4, name: Identifier(\"core\") }, function: 2, instruction: 90, function_name: Some(\"create_s_pool\") }))) in command 2",
> }
> 
## How to reproduce (on devnet)
1. Mint 2 Democoin (named tUSDT & tUSDC) at address `0x78d764de1b85ebed31253fd70206caf7a721bf4f7ab71eae31cd7c3335ba1d26` and `0x50693ee4856c7adcea62b4130998ca656ca717babaeb0721c3783bd182cfdc38` (CoinMetadata at `0xd9ee980596cbdcda084fb4d028b1fe01e76f87f56ad3d5ab0dd0e5654ed4706c` and `0xa2e2911ac01a5e5d9410ed3d2f985da2b8fef19ad393b018541b10c00b6a42b2`
2. Using sui client to call the create_s_pool method: `sui client call --gas-budget 80000000 --package= 366a6d402c05d5fce5fdc8b675e7bc6d02d52147195e625c702c313d85922ba4 --module=interface --function=create_s_pool --args 0xb1de967e11ddd71f8599d8f070221553a307c5e5de6ea11c9281eed7f09027a5 0x6 '[0x78d764de1b85ebed31253fd70206caf7a721bf4f7ab71eae31cd7c3335ba1d26]' '[0x50693ee4856c7adcea62b4130998ca656ca717babaeb0721c3783bd182cfdc38]' 1200 1000 0xd9ee980596cbdcda084fb4d028b1fe01e76f87f56ad3d5ab0dd0e5654ed4706c 0xa2e2911ac01a5e5d9410ed3d2f985da2b8fef19ad393b018541b10c00b6a42b2 --type-args 0xfcc7f581a640c07caf4823bb85393b0f9de93449c75a06ea6d4c6734ab90caf3::DemoCoin::DEMOCOIN 0xc16e7aab2df541af98d289c3daf2192b3d16018b76c2e96c20330f6ba2f4f055::DemoCoin::DEMOCOIN`
3. Error happened

**Comment by josemvcerqueira** [comment]
Hello @thaodx 

Can you please provide more information about the error?

I am not sure if passing vector via '[0x78d764de1b85ebed31253fd70206caf7a721bf4f7ab71eae31cd7c3335ba1d26]' works on the CLI.

We will deploy the DEX after the audit is done and I can get back to you on how this issue.

Thank you for your patience

**Comment by thaodx** [comment]
> Hello @thaodx
> 
> Can you please provide more information about the error?
> 
> I am not sure if passing vector via '[0x78d764de1b85ebed31253fd70206caf7a721bf4f7ab71eae31cd7c3335ba1d26]' works on the CLI.
> 
> We will deploy the DEX after the audit is done and I can get back to you about this issue.
> 
> Thank you for your patience

Hi @josemvcerqueira , passing vector on SUI client as my previous post is right, i was successfully create volatile pool on that way.

**Comment by josemvcerqueira** [comment]
> > Hello @thaodx
> > Can you please provide more information about the error?
> > I am not sure if passing vector via '[0x78d764de1b85ebed31253fd70206caf7a721bf4f7ab71eae31cd7c3335ba1d26]' works on the CLI.
> > We will deploy the DEX after the audit is done and I can get back to you about this issue.
> > Thank you for your patience
> 
> Hi @josemvcerqueira , passing vector on SUI client as my previous post is right, i was successfully create volatile pool on that way.

ah right! That makes sense. Odd, now I am very curious on what it could be!

Let me know if you find out before we deplay!

**Comment by thaodx** [comment]
> P.S. - It might be the fact that you passed low values. What are the decimals of each coin? Can you try to pass higher values?
> 
> for example if one coin has 6 decimals and you want to pass one coin, it has to be 1e6.

You're right, i need to pass bigger value to the pool, problem solved. Thank you @josemvcerqueira
